Stock warehouse distance
Numigi/odoo-stock-addons pull request #17
Opened 2019-12-11 20:52 UTC by ddufresne

https://www.numigi.com/web#id=17111&action=298&model=project.task&view_type=form&menu_id=200

2019-12-11 20:55 UTC, ddufresne commented on stock_warehouse_distance/models/stock_warehouse.py
> +from odoo import fields, models, _
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['odoo.fields' imported but unused](https://app.codacy.com/app/numigi/odoo-stock-addons/pullRequest?prid=4661186)

2019-12-11 20:55 UTC, ddufresne commented on stock_warehouse_distance/models/__init__.py
> +from . import (
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['.stock_warehouse_distance' imported but unused](https://app.codacy.com/app/numigi/odoo-stock-addons/pullRequest?prid=4661186)

2019-12-11 20:55 UTC, ddufresne commented on stock_warehouse_distance/models/stock_warehouse.py
> +from odoo import fields, models, _
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused fields imported from odoo](https://app.codacy.com/app/numigi/odoo-stock-addons/pullRequest?prid=4661186)

2019-12-12 16:43 UTC, foutoucour requested changes
2 commentaires mineures. À toi de voir si tu veux les accepter. Tu peux merger derrière.

2019-12-12 16:43 UTC, foutoucour commented on stock_warehouse_distance/README.rst
> +Kilometers
```suggestion
Units
```

2019-12-12 16:43 UTC, foutoucour commented on stock_warehouse_distance/README.rst
> +Reflexive
```suggestion
Reflexivity
```

2019-12-13 21:27 UTC, merged