12.0 stock picking change destination (TA#19944)
Numigi/odoo-stock-addons pull request #22
Opened 2020-03-27 14:36 UTC by foutoucour

En attente de la definition du message d'erreur dans le cas de warehouse différentes.
Le reste je te laisse me dire.

2020-03-27 15:22 UTC, ddufresne requested changes

2020-03-27 15:22 UTC, ddufresne commented on stock_picking_change_destination/models/stock_picking.py
> +wizard_model = "stock.picking.change.destination"
@foutoucour personnellement, je préfère séparer les modèles par fichier. Ça facilite la recherche dans le module.

2020-03-27 15:22 UTC, ddufresne commented on stock_picking_change_destination/models/stock_picking.py
> +                    destination_moves=", ".join(destination_moves.mapped('display_name'))
@foutoucour c'est mieux de donner le nom des pickings liés plutôt que les mouvements liés. Ça serait plus cohérent avec le message et c'est plus utile comme information pour l'utilisateur.

2020-03-27 15:22 UTC, ddufresne commented on stock_picking_change_destination/models/stock_picking.py
> +            picking = self.env["stock.picking"].browse(self.picking_id.id)
@foutoucour pourquoi le browse?

2020-03-27 15:22 UTC, ddufresne commented on stock_picking_change_destination/models/stock_picking.py
> +        return self.move_lines.move_dest_ids
Ici, ça fail si plusieurs move_lines.

self.mapped('move_lines.move_dest_ids')

2020-03-27 15:22 UTC, ddufresne commented on stock_picking_change_destination/models/stock_picking.py
> +            move.location_dest_id = self.location_dest_id.id
Le ``.id`` n'est pas requis.

move.location_dest_id = self.location_dest_id.id

2020-03-27 15:22 UTC, ddufresne commented on stock_picking_change_destination/models/stock_picking.py
> +            move.location_dest_id = self.location_dest_id.id
Ça peut même être simplifié pour:

self.move_lines.write({'location_dest_id': self.location_dest_id.id})

Cela combine les requêtes à la bd.

2020-03-27 15:22 UTC, ddufresne commented on stock_picking_change_destination/tests/test_stock_picking.py
> +        )
@foutoucour je me rend compte qu'il y a une contrainte qui n'a probablement pas été spécifiée.

Lorsque des quantités de stock sont réservées par le picking, le changement de destination devrait être bloqué.

Le plus simple pour régler cette problématique est d'empêcher le changement de destination si le picking contient des stock.move.line (champ move_line_ids).

Je te laisse en discuter avec Quentin au besoin.

2020-03-27 15:28 UTC, ddufresne commented on stock_picking_change_destination/tests/test_stock_picking.py
> +        )
@foutoucour je me mélange ici. Il n'y a pas de contrainte à ajouter.

Il faut juste propager l'emplacement de destination sur les stock.move.line.

2020-03-30 14:06 UTC, foutoucour commented
@ddufresne j'ai fait les changements. Dit moi.

2020-03-30 14:08 UTC, ddufresne commented on stock_picking_change_destination/tests/test_stock_picking.py
> +import datetime
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused import datetime](https://app.codacy.com/manual/numigi/odoo-stock-addons/pullRequest?prid=5259061)

2020-03-30 14:26 UTC, ddufresne commented
@foutoucour excellent, bon travail!

2020-03-30 14:26 UTC, ddufresne approved these changes

2020-03-30 14:26 UTC, merged