TA#21651 Stock component account
Numigi/odoo-stock-addons pull request #25
Opened 2020-04-06 16:58 UTC by ddufresne

2020-04-06 16:59 UTC, ddufresne commented on stock_component_account/tests/test_stock_move.py
> +from odoo.exceptions import ValidationError
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused ValidationError imported from odoo.exceptions](https://app.codacy.com/manual/numigi/odoo-stock-addons/pullRequest?prid=5314676)

2020-04-06 16:59 UTC, ddufresne commented on stock_component_account/models/stock_move_line.py
> +from odoo import fields, models
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused fields imported from odoo](https://app.codacy.com/manual/numigi/odoo-stock-addons/pullRequest?prid=5314676)

2020-04-06 16:59 UTC, ddufresne commented on stock_component/models/stock_production_lot.py
> +    def _get_component_move_name(self, serial, parent_move):
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method could be a function](https://app.codacy.com/manual/numigi/odoo-stock-addons/pullRequest?prid=5314676)

2020-04-06 16:59 UTC, ddufresne commented on stock_component_account/tests/test_stock_move.py
> +import pytest
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused import pytest](https://app.codacy.com/manual/numigi/odoo-stock-addons/pullRequest?prid=5314676)

2020-04-06 17:00 UTC, ddufresne commented on stock_component_account/models/product_product.py
> +    def _compute_average_price_including_components(self, qty_done, quantity, moves):
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method could be a function](https://app.codacy.com/manual/numigi/odoo-stock-addons/pullRequest?prid=5314676)

2020-04-07 17:35 UTC, foutoucour requested changes
que des améliorations de la lisibilité du code. Le reste les tests sont là ;)

2020-04-07 17:35 UTC, foutoucour commented on stock_component_account/README.rst
> +Customer Invoices
Peut être renommé la section par Journal Entry.
J'ai trouvé ça confu que le titre soit sur Invoices mais qu'on parle presque de Journal Entry

2020-04-07 17:35 UTC, foutoucour commented on stock_component_account/models/stock_move.py
> +            lambda i: i.account_id.reconcile
Est ce que tu pourrais extraire cette logique dans une variable / methode pour rendre plus explicite l'intention ?

2020-04-07 17:35 UTC, foutoucour commented on stock_component_account/models/stock_move.py
> +        new_component_item = move.line_ids.sorted("id")[0]
pourquoi uniquement le premier résultat ?

2020-04-07 17:35 UTC, foutoucour commented on stock_component_account/models/stock_move_line.py
> +from odoo import fields, models
```suggestion
from odoo import models
```

2020-04-07 17:35 UTC, foutoucour commented on stock_component_account/tests/test_stock_move.py
> +import pytest
```suggestion
```

2020-04-07 17:35 UTC, foutoucour commented on stock_component_account/tests/test_stock_move.py
> +from odoo.exceptions import ValidationError
```suggestion
```

2020-04-07 17:35 UTC, foutoucour commented on stock_component_account/tests/test_stock_move.py
> +    def setUpClass(cls):
c'est un big setup ça :)
Il serait intéressant de splitter la methode pour faciliter la compréhension de l'intention du setup.
Est ce que tu penses que ça aiderai ?

2020-04-07 17:35 UTC, foutoucour commented on stock_component_account/tests/test_stock_move.py
> +            cls._select_serial_on_stock_move(serial, move)
Je suis pas sûr du nom de la fonction ici, mais je vois pas guere mieux.
Le terme `_select` me fait penser à de la GUI.

2020-04-07 17:35 UTC, foutoucour commented on stock_component_account/tests/test_stock_move.py
> +    @data((0, 0), (0, 1), (1, 1))
Quel est le comportement avec un chiffre négatif ?

2020-04-07 17:35 UTC, foutoucour commented on stock_component_account/tests/test_stock_move.py
> +    @data(
même chose. Est ce qu'on pourrait rajouter des nombres négatifs pour vérifier que le comportement ? Où c'est totalement impossible que ça arrive ?

2020-04-07 17:35 UTC, foutoucour commented on stock_component_account/tests/test_stock_move.py
> +        self, qty_done, quantity, expected_average_price
Sacré black ;)

2020-04-07 17:35 UTC, foutoucour commented on stock_component_account/tests/test_stock_move.py
> +        # 3 moves for P1
Ces commentaires seraient peut être mieux en docstring

2020-04-07 17:35 UTC, foutoucour commented on stock_component_account/tests/test_stock_move.py
> +        # 3 + 3 + 2 moves for P1
same

2020-04-07 18:18 UTC, ddufresne commented on stock_component_account/models/stock_move_line.py
> +from odoo import fields, models
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused fields imported from odoo](https://app.codacy.com/manual/numigi/odoo-stock-addons/pullRequest?prid=5314676)

2020-04-07 18:18 UTC, ddufresne commented on stock_component_account/tests/test_stock_move.py
> +import pytest
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused import pytest](https://app.codacy.com/manual/numigi/odoo-stock-addons/pullRequest?prid=5314676)

2020-04-07 18:18 UTC, ddufresne commented on stock_component/models/stock_production_lot.py
> +    def _get_component_move_name(self, serial, parent_move):
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method could be a function](https://app.codacy.com/manual/numigi/odoo-stock-addons/pullRequest?prid=5314676)

2020-04-07 18:18 UTC, ddufresne commented on stock_component_account/tests/test_stock_move.py
> +from odoo.exceptions import ValidationError
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused ValidationError imported from odoo.exceptions](https://app.codacy.com/manual/numigi/odoo-stock-addons/pullRequest?prid=5314676)

2020-04-07 18:18 UTC, ddufresne commented on stock_component_account/models/product_product.py
> +    def _compute_average_price_including_components(self, qty_done, quantity, moves):
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method could be a function](https://app.codacy.com/manual/numigi/odoo-stock-addons/pullRequest?prid=5314676)

2020-04-07 18:21 UTC, ddufresne commented on stock_component_account/models/stock_move.py
> +        new_component_item = move.line_ids.sorted("id")[0]
@foutoucour la première ligne est celle correspondant à la composante.
Cette ligne doit être réconciliée.

La deuxième est celle correspondant à l'équipement parent.
Elle ne doit pas être réconciliée.

Il n'y a pas de manière à coup sûr d'identifier ces lignes autre que par leur index.

2020-04-07 18:29 UTC, ddufresne commented on stock_component_account/tests/test_stock_move.py
> +    @data((0, 0), (0, 1), (1, 1))
@foutoucour excellent point, merci.

2020-04-07 18:57 UTC, ddufresne commented on stock_component_account/tests/test_stock_move.py
> +from odoo.exceptions import ValidationError
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused ValidationError imported from odoo.exceptions](https://app.codacy.com/manual/numigi/odoo-stock-addons/pullRequest?prid=5314676)

2020-04-07 18:57 UTC, ddufresne commented on stock_component_account/models/product_product.py
> +    def _compute_average_price_including_components(self, qty_done, quantity, moves):
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method could be a function](https://app.codacy.com/manual/numigi/odoo-stock-addons/pullRequest?prid=5314676)

2020-04-07 18:57 UTC, ddufresne commented on stock_component/models/stock_production_lot.py
> +    def _get_component_move_name(self, serial, parent_move):
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method could be a function](https://app.codacy.com/manual/numigi/odoo-stock-addons/pullRequest?prid=5314676)

2020-04-08 14:21 UTC, ddufresne commented on stock_component_account/README.rst
> +Customer Invoices
@foutoucour fixed

2020-04-08 14:33 UTC, foutoucour approved these changes

2020-04-08 14:35 UTC, ddufresne commented on stock_component_account/models/stock_move.py
> +            lambda i: i.account_id.reconcile
@foutoucour fixed

2020-04-08 14:35 UTC, ddufresne commented on stock_component_account/tests/test_stock_move.py
> +    @data((0, 0), (0, 1), (1, 1))
c'est corrigé

2020-04-08 14:35 UTC, ddufresne commented on stock_component_account/tests/test_stock_move.py
> +        # 3 moves for P1
corrigé

2020-04-08 14:35 UTC, ddufresne commented on stock_component_account/tests/test_stock_move.py
> +        # 3 + 3 + 2 moves for P1
corrigé

2020-04-08 14:37 UTC, ddufresne commented on stock_component_account/models/product_product.py
> +    def _compute_average_price_including_components(self, qty_done, quantity, moves):
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method could be a function](https://app.codacy.com/manual/numigi/odoo-stock-addons/pullRequest?prid=5314676)

2020-04-08 14:37 UTC, ddufresne commented on stock_component/models/stock_production_lot.py
> +    def _get_component_move_name(self, serial, parent_move):
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Method could be a function](https://app.codacy.com/manual/numigi/odoo-stock-addons/pullRequest?prid=5314676)

2020-04-08 14:37 UTC, ddufresne commented on stock_component_account/tests/test_stock_move.py
> +from odoo.exceptions import ValidationError
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused ValidationError imported from odoo.exceptions](https://app.codacy.com/manual/numigi/odoo-stock-addons/pullRequest?prid=5314676)

2020-04-08 14:49 UTC, merged