TA#34968
Numigi/odoo-stock-addons pull request #51
Opened 2021-05-26 21:23 UTC by gabgosrob

2021-05-27 11:05 UTC, ddufresne requested changes

2021-05-27 11:05 UTC, ddufresne commented on stock_auto_assign_disabled_jit/tests/test_auto_assign.py
> +        assert self.stock_move.reserved_availability == 0.0
@gabgosrob dans ton test unitaire, ça aurait dû être la confirmation d'un sale.order qui est lancée à la ligne 51.

Lorsque self.stock_move._action_confirm() est lancé manuellement, la réservation devrait fonctionner.

2021-05-27 13:50 UTC, gabgosrob commented on stock_auto_assign_disabled_jit/tests/test_auto_assign.py
> +        assert self.stock_move.reserved_availability == 0.0
C'est ce que j'ai fait dans les tests de stock_auto_assign_disabled aussi, c'est différent dans ce cas-ci?

2021-05-27 15:45 UTC, ddufresne commented on stock_auto_assign_disabled_jit/tests/test_auto_assign.py
> +        assert self.stock_move.reserved_availability == 0.0
assert self.order_line.move_ids.reserved_availability == 0

2021-05-27 19:04 UTC, ddufresne approved these changes

2021-05-27 20:25 UTC, gabgosrob commented
Rajouter option dans la selection "vide" pour que la desactivation de reservation ne se fasse pas directement apres l'installation

2021-05-31 12:31 UTC, ddufresne approved these changes
@gabgosrob excellent, merci pour les changements.

2021-06-09 21:52 UTC, gabgosrob commented on stock_auto_assign_disabled_jit/tests/test_auto_assign.py
> +    def test_reservation(self):
Ce test ne pas pas si on ne met pas le setting à "off" explicitement même si c'est supposé être l'option par défaut. À voir

2021-06-09 21:52 UTC, gabgosrob commented on stock_auto_assign_disabled/tests/test_auto_assign.py
> +    def test_scheduler_off(self):
Même chose que ligne 58 des tests de stock_auto_assign_disabled_jit

2021-06-10 14:30 UTC, ddufresne commented on stock_auto_assign_disabled/models/stock_move.py
> +            "stock_auto_assign_disabled.config"
```suggestion
            "stock_auto_assign_disabled.config", "off"
```

2021-06-11 14:26 UTC, merged