TA#51597 [ADD] stock_picking_secondary_unit_demand : secondary unit demand on picking
Numigi/odoo-stock-addons pull request #96
Opened 2023-05-09 06:16 UTC by lanto-razafindrabe

2023-05-09 15:06 UTC, majouda requested changes

2023-05-09 15:06 UTC, majouda commented on stock_picking_secondary_unit_demand/models/stock_move.py
> +        compute="_compute_merged_qty_uom_info"
Hello @lanto-razafindrabe 

Ce que tu as fait est correct mais je me demande si c'est plus optimale de faire 2 champs related au lieu du compute (un champ pour la valeur et le 2eme pour l'unité de mesure) et voir après comment les afficher sur une seule colonne dans la vue liste?

2023-05-09 15:06 UTC, majouda commented on stock_picking_secondary_unit_demand/models/stock_move_line.py
> +        compute="_compute_merged_qty_uom_info"
Même remarque pour le champs précédent.

2023-05-09 15:16 UTC, lanto-razafindrabe commented on stock_picking_secondary_unit_demand/models/stock_move.py
> +        compute="_compute_merged_qty_uom_info"
> Hello @lanto-razafindrabe
> 
> Ce que tu as fait est correct mais je me demande si c'est plus optimale de faire 2 champs related au lieu du compute (un champ pour la valeur et le 2eme pour l'unité de mesure) et voir après comment les afficher sur une seule colonne dans la vue liste?

hello @majouda 
Ce que j'ai fait tout au début, c'était avec cette approche. Puis, je me suis demandée, avec ça j'ai trois champs, au lieu d'un champ. Le code sera plus court. J'ai gardé l'ancienne version si besoin.

On peut en discuter pour voir en détail le contexte si besoin. Et voir, si je dois ré ajuster les codes.

Un aperçu..
![image](https://github.com/Numigi/odoo-stock-addons/assets/124650562/69e23831-48e8-4d51-b2b0-dfadf679a38c)

2023-05-10 15:02 UTC, majouda commented on stock_picking_secondary_unit_demand/models/stock_move.py
> +        compute="_compute_merged_qty_uom_info"
@lanto-razafindrabe 
Malheureusement je ne trouve pas une meilleure option pour afficher les 2 champs dans une seule colonne sans passer par un compute ou un traitement Js. ca va être plus long.

2023-05-10 15:02 UTC, majouda approved these changes

2023-05-10 15:02 UTC, merged

2023-05-10 16:16 UTC, lanto-razafindrabe commented on stock_picking_secondary_unit_demand/models/stock_move.py
> +        compute="_compute_merged_qty_uom_info"
> @lanto-razafindrabe Malheureusement je ne trouve pas une meilleure option pour afficher les 2 champs dans une seule colonne sans passer par un compute ou un traitement Js. ca va être plus long.

@majouda 
C'est dommage alors. On reste sur ce qui est déjà fait alors. Tout à fait, avec un Js c'est une autre option aussi, mais c'est long pour le budget qu'on a. Merci.